### ISSUE TITLE
Firefox URI Leak

### ISSUE THREAD

**Issue by sueridgepipe** [dillbyrne/random-agent-spoofer#422]
Lots of fingerprint browser info available via resource://, details here.

http://www.ghacks.net/2016/06/12/firefox-resource-leak/

Possible to stop this leak in a future RAS version?

**Comment by Wannabe-Programmer** [comment]
The [No Resource URI Leak](https://addons.mozilla.org/en-US/firefox/addon/no-resource-uri-leak/) fixed the issue. 

Here is the source code used: https://addons.mozilla.org/en-US/firefox/files/browse/445831/

**Comment by beardog108** [comment]
RAS should add the same fix as an option.

**Comment by dillbyrne** [comment]
This has been fixed in ff48 so there is no point in adding it to RAS now as that will be out by the time I get the next version ready and it is better to have it handled in the browser itself.

![ff48](https://i.imgur.com/Fnc7z1Q.png)

**Comment by NiklasGollenstede** [comment]
![leak](https://cloud.githubusercontent.com/assets/10552031/18256936/4203f25a-73bc-11e6-8373-6ede2bb53f0d.png)

Sorry to disappoint, but the test is just buggy (for a time it didn't work with 64bit FF). But as you see the problem is not solved (by Firefox itself)
